spring:
  application:
    name: spot-media v0.1

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: c2830934.ferozo.com
    port: 465
    username: gonzalo@spotmediainc.com
    password: Incmedia@2025
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
        debug: true

app:
  mail:
    contact-recipient: gonzalo@spotmediainc.com

server:
  port: 3000
